[workspace]

members = [
    "part01",
    "part02",
    "part03",
    "part04",
    "part05",
    "part06",
    "part07",
    "part08",
    "part09",
    "part10",
    "part11",
    "part12",
    "part13",
    "part16",
    "part17",
    "part18",
    "part19",
    "part23",
]
