[package]
name = "part04"
version = "0.1.0"
authors = ["jflinter <jflinter11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
strum = "0.20"
strum_macros = "0.20"